typography_spectrum: 0.738567715510726
color:
  brandStrength: 0.3029641460161656
  lightness: 0.6307181199081242
  saturation: 0.7267172550782561
  rhythmicContrast: 0.8465436093974859
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
layout_spectrum: 0.5086906063370407
name: A trial with fabric | ch
style: taylor
navigation:
  - name: My company
    url: 'http://www.fabric.ch'
    type: external
  - name: Public Platform of Future-Past
    id: f2f3e7d3-72cb-44fd-a57d-3957e756ba19
    type: content
title: Hello World Indeed
description: Cheers
